# Generated by Django 3.2.5 on 2021-07-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='category',
        ),
        migrations.AddField(
            model_name='choice',
            name='type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiced',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='quest',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
