# Generated by Django 3.2.5 on 2021-07-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210709_2146'),
        ('users', '0003_auto_20210712_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='avaliation',
            field=models.ManyToManyField(to='profiles.Avaliation'),
        ),
    ]
