# Generated by Django 3.2.5 on 2021-07-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210709_2146'),
        ('users', '0004_teams_avaliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='avaliation',
            field=models.ManyToManyField(blank=True, to='profiles.Avaliation'),
        ),
    ]
