# Generated by Django 3.2.5 on 2021-07-12 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_teams_avaliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='test',
        ),
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
