# Generated by Django 3.2.5 on 2021-07-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210709_2146'),
        ('users', '0006_auto_20210712_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='type',
        ),
        migrations.AddField(
            model_name='choice',
            name='category',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='profiles.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiced',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='choiced', to='profiles.answers'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='quest',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='profiles.question'),
        ),
    ]
