# Generated by Django 3.2.5 on 2021-07-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210712_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='category',
        ),
    ]
