# Generated by Django 3.2.5 on 2021-07-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210712_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
