# Generated by Django 3.2.5 on 2021-07-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_teams_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='avaliation',
        ),
    ]
