# Generated by Django 3.2.5 on 2021-07-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210709_2146'),
        ('users', '0015_auto_20210712_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='avaliations',
            field=models.ManyToManyField(related_name='avaliations', to='profiles.Avaliation'),
        ),
    ]
