# Generated by Django 3.2.5 on 2021-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_teams_avaliations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Profile'),
        ),
    ]
