# Generated by Django 3.2.5 on 2021-07-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_teams_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='teste.png', upload_to='companies/'),
        ),
    ]
