# Generated by Django 3.2.5 on 2021-07-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='teste.jpg', upload_to='companies/'),
        ),
    ]
