# Generated by Django 3.2.5 on 2021-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiced',
            field=models.CharField(max_length=300),
        ),
    ]
