# Generated by Django 3.2.5 on 2021-07-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210708_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='profiles.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='avaliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliation', to='profiles.avaliation'),
        ),
    ]
