# Generated by Django 3.2.5 on 2021-07-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210708_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='profiles.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='avaliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='profiles.avaliation'),
        ),
    ]
