# Generated by Django 3.2.5 on 2021-07-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210708_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='avaliation',
        ),
        migrations.AddField(
            model_name='category',
            name='avaliation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avaliation', to='profiles.avaliation'),
            preserve_default=False,
        ),
    ]
