# Generated by Django 3.2.5 on 2021-07-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210709_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='avaliation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='avaliation',
            name='category',
            field=models.ManyToManyField(related_name='category', to='profiles.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='profiles.Question'),
        ),
    ]
