# Generated by Django 3.2.5 on 2021-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_avaliation_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliation',
            name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.CharField(blank=True, choices=[('pontuação', 'pontuação'), ('representação', 'representação')], default='pontuação', max_length=20),
        ),
    ]
